### ISSUE TITLE
[Bug] Custom location doesn't set and save

### ISSUE THREAD

**Issue by julianfairfax** [Aries-Sciences-LLC/Sleek-Weather#1]
If you use location services to set your location, it works fine but requires location services to be turned on everytime you open the app because it doesn't save. If you set a custom location when opening the app, it just doesn't work. If you use location services when opening the app, then set a custom location, it works fine, but requires you to set it again everytine you open the app because it doesn't save either.

In summary: when opening the app, only location services can get you past the location selection screen, and that location along with any custom location you select afterwards doesn't save so you have to keep location services on and select the custom location again when you next open the app.

Hopefully this can be fixed somehow because Sleek Weather is the one of if not the only open source weather app using OpenWeatherMap that I could find on the App Store. I haven't tried it yet but Quick Weather Mac app also looks quite nice. Thank you so much for making both of these wonderful apps and thanks for your help!

**Comment by julian-fairfax** [comment]
I'm no longer using this app so you can ignore this.

**Comment by ozanm** [comment]
Hey Julian,

Thanks for discovering the bug. Its an interesting problem and one that I kind of expected/was worried about but always overlooked because it happened to work on the one device that I use. If I remember correctly, I designed the flow to first secure a list of location of sorts before retrieving the weather data which is before any UI is loaded. I think that I designed the location and geolocation system to check if there is already a saved list in the UserDefaults (and if there isn't then fetch their current location and create one with it--and if geolocation doesn't work present a location search view controller). It looks like it gets confused where it first checks if location services are off before it checks if there is already a saved list. The opposite should be the case.

I'll make sure to update it soon. However, if you would like to tackle the bug yourself, you are more than welcome to. And if so, let me know if there is any help you might need or any information you might need from me. I'd be more than happy to provide it.

Thanks,
Ozan Mirza

**Comment by julianfairfax** [comment]
> Hey Julian,
> 
> Thanks for discovering the bug. Its an interesting problem and one that I kind of expected/was worried about but always overlooked because it happened to work on the one device that I use. If I remember correctly, I designed the flow to first secure a list of location of sorts before retrieving the weather data which is before any UI is loaded. I think that I designed the location and geolocation system to check if there is already a saved list in the UserDefaults (and if there isn't then fetch their current location and create one with it--and if geolocation doesn't work present a location search view controller). It looks like it gets confused where it first checks if location services are off before it checks if there is already a saved list. The opposite should be the case.
> 

Thanks for the in-depth explanation!
> I'll make sure to update it soon. However, if you would like to tackle the bug yourself, you are more than welcome to. And if so, let me know if there is any help you might need or any information you might need from me. I'd be more than happy to provide it.
> 

Unfortunately that's out of the scope of my abilities since I don't have a Mac but I'm looking forward to using it again when you've had some time to fix it. Thanks for your work on this wonderful app!

**Comment by julianfairfax** [comment]
I'm no longer using this app so you can ignore this. (I still love the app, I've just switched away from using iOS)
